[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "ff-emote-api"
